// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

class constants$19 {

    static final FunctionDescriptor WebPDemuxPrevFrame$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDemuxPrevFrame$MH = RuntimeHelper.downcallHandle(
        "WebPDemuxPrevFrame",
        constants$19.WebPDemuxPrevFrame$FUNC, false
    );
    static final FunctionDescriptor WebPDemuxReleaseIterator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDemuxReleaseIterator$MH = RuntimeHelper.downcallHandle(
        "WebPDemuxReleaseIterator",
        constants$19.WebPDemuxReleaseIterator$FUNC, false
    );
    static final FunctionDescriptor WebPDemuxGetChunk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDemuxGetChunk$MH = RuntimeHelper.downcallHandle(
        "WebPDemuxGetChunk",
        constants$19.WebPDemuxGetChunk$FUNC, false
    );
    static final FunctionDescriptor WebPDemuxNextChunk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDemuxNextChunk$MH = RuntimeHelper.downcallHandle(
        "WebPDemuxNextChunk",
        constants$19.WebPDemuxNextChunk$FUNC, false
    );
    static final FunctionDescriptor WebPDemuxPrevChunk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDemuxPrevChunk$MH = RuntimeHelper.downcallHandle(
        "WebPDemuxPrevChunk",
        constants$19.WebPDemuxPrevChunk$FUNC, false
    );
    static final FunctionDescriptor WebPDemuxReleaseChunkIterator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDemuxReleaseChunkIterator$MH = RuntimeHelper.downcallHandle(
        "WebPDemuxReleaseChunkIterator",
        constants$19.WebPDemuxReleaseChunkIterator$FUNC, false
    );
}


