// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import jdk.incubator.foreign.FunctionDescriptor;

import java.lang.invoke.MethodHandle;

class constants$17 {

    static final FunctionDescriptor flsll$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle flsll$MH = RuntimeHelper.downcallHandle(
        "flsll",
        constants$17.flsll$FUNC, false
    );
    static final FunctionDescriptor WebPDataInit$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDataInit$MH = RuntimeHelper.downcallHandle(
        "WebPDataInit",
        constants$17.WebPDataInit$FUNC, false
    );
    static final FunctionDescriptor WebPDataClear$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDataClear$MH = RuntimeHelper.downcallHandle(
        "WebPDataClear",
        constants$17.WebPDataClear$FUNC, false
    );
    static final FunctionDescriptor WebPDataCopy$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDataCopy$MH = RuntimeHelper.downcallHandle(
        "WebPDataCopy",
        constants$17.WebPDataCopy$FUNC, false
    );
    static final FunctionDescriptor WebPGetDemuxVersion$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle WebPGetDemuxVersion$MH = RuntimeHelper.downcallHandle(
        "WebPGetDemuxVersion",
        constants$17.WebPGetDemuxVersion$FUNC, false
    );
    static final FunctionDescriptor WebPDemuxInternal$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPDemuxInternal$MH = RuntimeHelper.downcallHandle(
        "WebPDemuxInternal",
        constants$17.WebPDemuxInternal$FUNC, false
    );
}


