// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama.webpdemux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final VarHandle const$0 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("flip"));
    static final VarHandle const$1 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("alpha_dithering_strength"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("has_alpha"),
            JAVA_INT.withName("has_animation"),
            JAVA_INT.withName("format"),
            MemoryLayout.sequenceLayout(5, JAVA_INT).withName("pad")
        ).withName("input"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("colorspace"),
            JAVA_INT.withName("width"),
            JAVA_INT.withName("height"),
            JAVA_INT.withName("is_external_memory"),
            MemoryLayout.unionLayout(
                MemoryLayout.structLayout(
                    RuntimeHelper.POINTER.withName("rgba"),
                    JAVA_INT.withName("stride"),
                    MemoryLayout.paddingLayout(4),
                    JAVA_LONG.withName("size")
                ).withName("RGBA"),
                MemoryLayout.structLayout(
                    RuntimeHelper.POINTER.withName("y"),
                    RuntimeHelper.POINTER.withName("u"),
                    RuntimeHelper.POINTER.withName("v"),
                    RuntimeHelper.POINTER.withName("a"),
                    JAVA_INT.withName("y_stride"),
                    JAVA_INT.withName("u_stride"),
                    JAVA_INT.withName("v_stride"),
                    JAVA_INT.withName("a_stride"),
                    JAVA_LONG.withName("y_size"),
                    JAVA_LONG.withName("u_size"),
                    JAVA_LONG.withName("v_size"),
                    JAVA_LONG.withName("a_size")
                ).withName("YUVA")
            ).withName("u"),
            MemoryLayout.sequenceLayout(4, JAVA_INT).withName("pad"),
            RuntimeHelper.POINTER.withName("private_memory")
        ).withName("output"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("bypass_filtering"),
            JAVA_INT.withName("no_fancy_upsampling"),
            JAVA_INT.withName("use_cropping"),
            JAVA_INT.withName("crop_left"),
            JAVA_INT.withName("crop_top"),
            JAVA_INT.withName("crop_width"),
            JAVA_INT.withName("crop_height"),
            JAVA_INT.withName("use_scaling"),
            JAVA_INT.withName("scaled_width"),
            JAVA_INT.withName("scaled_height"),
            JAVA_INT.withName("use_threads"),
            JAVA_INT.withName("dithering_strength"),
            JAVA_INT.withName("flip"),
            JAVA_INT.withName("alpha_dithering_strength"),
            MemoryLayout.sequenceLayout(5, JAVA_INT).withName("pad")
        ).withName("options"),
        MemoryLayout.paddingLayout(4)
    ).withName("WebPDecoderConfig");
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "WebPInitDecoderConfigInternal",
        constants$14.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "WebPIDecode",
        constants$21.const$4
    );
}


