// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama.webpdemux;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$30 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$30() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "memset_pattern4",
        constants$30.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "memset_pattern8",
        constants$30.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "memset_pattern16",
        constants$30.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "strcasestr",
        constants$23.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "strnstr",
        constants$22.const$5
    );
}


