// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$22 {

    static final MemorySegment __PRI_64_LENGTH_MODIFIER__$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ll");
    static final MemorySegment __SCN_64_LENGTH_MODIFIER__$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ll");
    static final MemorySegment __PRI_MAX_LENGTH_MODIFIER__$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("j");
    static final MemorySegment __SCN_MAX_LENGTH_MODIFIER__$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("j");
    static final MemorySegment PRId8$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("hhd");
    static final MemorySegment PRIi8$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("hhi");
}


