// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$3 {

    static final FunctionDescriptor WebPDecodeBGRAInto$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPDecodeBGRAInto$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeBGRAInto",
        constants$3.WebPDecodeBGRAInto$FUNC
    );
    static final FunctionDescriptor WebPDecodeRGBInto$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPDecodeRGBInto$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeRGBInto",
        constants$3.WebPDecodeRGBInto$FUNC
    );
    static final FunctionDescriptor WebPDecodeBGRInto$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPDecodeBGRInto$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeBGRInto",
        constants$3.WebPDecodeBGRInto$FUNC
    );
    static final FunctionDescriptor WebPDecodeYUVInto$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPDecodeYUVInto$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeYUVInto",
        constants$3.WebPDecodeYUVInto$FUNC
    );
    static final FunctionDescriptor WebPIsPremultipliedMode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPIsPremultipliedMode$MH = RuntimeHelper.downcallHandle(
        "WebPIsPremultipliedMode",
        constants$3.WebPIsPremultipliedMode$FUNC
    );
    static final FunctionDescriptor WebPIsAlphaMode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPIsAlphaMode$MH = RuntimeHelper.downcallHandle(
        "WebPIsAlphaMode",
        constants$3.WebPIsAlphaMode$FUNC
    );
}


