// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2 {

    static final FunctionDescriptor WebPDecodeBGRA$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDecodeBGRA$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeBGRA",
        constants$2.WebPDecodeBGRA$FUNC
    );
    static final FunctionDescriptor WebPDecodeRGB$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDecodeRGB$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeRGB",
        constants$2.WebPDecodeRGB$FUNC
    );
    static final FunctionDescriptor WebPDecodeBGR$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDecodeBGR$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeBGR",
        constants$2.WebPDecodeBGR$FUNC
    );
    static final FunctionDescriptor WebPDecodeYUV$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle WebPDecodeYUV$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeYUV",
        constants$2.WebPDecodeYUV$FUNC
    );
    static final FunctionDescriptor WebPDecodeRGBAInto$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPDecodeRGBAInto$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeRGBAInto",
        constants$2.WebPDecodeRGBAInto$FUNC
    );
    static final FunctionDescriptor WebPDecodeARGBInto$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle WebPDecodeARGBInto$MH = RuntimeHelper.downcallHandle(
        "WebPDecodeARGBInto",
        constants$2.WebPDecodeARGBInto$FUNC
    );
}


