// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct heif_content_light_level {
 *     uint16_t max_content_light_level;
 *     uint16_t max_pic_average_light_level;
 * }
 * }
 */
public class heif_content_light_level {

    heif_content_light_level() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        heif_h.C_SHORT.withName("max_content_light_level"),
        heif_h.C_SHORT.withName("max_pic_average_light_level")
    ).withName("heif_content_light_level");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort max_content_light_level$LAYOUT = (OfShort)$LAYOUT.select(groupElement("max_content_light_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t max_content_light_level
     * }
     */
    public static final OfShort max_content_light_level$layout() {
        return max_content_light_level$LAYOUT;
    }

    private static final long max_content_light_level$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t max_content_light_level
     * }
     */
    public static final long max_content_light_level$offset() {
        return max_content_light_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t max_content_light_level
     * }
     */
    public static short max_content_light_level(MemorySegment struct) {
        return struct.get(max_content_light_level$LAYOUT, max_content_light_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t max_content_light_level
     * }
     */
    public static void max_content_light_level(MemorySegment struct, short fieldValue) {
        struct.set(max_content_light_level$LAYOUT, max_content_light_level$OFFSET, fieldValue);
    }

    private static final OfShort max_pic_average_light_level$LAYOUT = (OfShort)$LAYOUT.select(groupElement("max_pic_average_light_level"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t max_pic_average_light_level
     * }
     */
    public static final OfShort max_pic_average_light_level$layout() {
        return max_pic_average_light_level$LAYOUT;
    }

    private static final long max_pic_average_light_level$OFFSET = 2;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t max_pic_average_light_level
     * }
     */
    public static final long max_pic_average_light_level$offset() {
        return max_pic_average_light_level$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t max_pic_average_light_level
     * }
     */
    public static short max_pic_average_light_level(MemorySegment struct) {
        return struct.get(max_pic_average_light_level$LAYOUT, max_pic_average_light_level$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t max_pic_average_light_level
     * }
     */
    public static void max_pic_average_light_level(MemorySegment struct, short fieldValue) {
        struct.set(max_pic_average_light_level$LAYOUT, max_pic_average_light_level$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

