// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_once_t __darwin_pthread_once_t;
 *}
 */
public final class __darwin_pthread_once_t extends _opaque_pthread_once_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private __darwin_pthread_once_t() {
    }
}


