// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {
    }

    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "strerror",
        constants$25.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "strlen",
        constants$25.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "strncat",
        constants$22.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "strncmp",
        constants$16.const$1
    );
}


