// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$20 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$20() {
    }

    static final VarHandle const$0 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("crop_height"));
    static final VarHandle const$1 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("use_scaling"));
    static final VarHandle const$2 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("scaled_width"));
    static final VarHandle const$3 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("scaled_height"));
    static final VarHandle const$4 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("use_threads"));
    static final VarHandle const$5 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("dithering_strength"));
}


