// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;

final class constants$38 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$38() {
    }

    static final VarHandle const$0 = constants$36.const$2.varHandle(MemoryLayout.PathElement.groupElement("has_alpha"));
    static final VarHandle const$1 = constants$36.const$2.varHandle(MemoryLayout.PathElement.groupElement("blend_method"));
    static final VarHandle const$2 = constants$36.const$2.varHandle(MemoryLayout.PathElement.groupElement("private_"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "WebPDemuxGetFrame",
        constants$38.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "WebPDemuxNextFrame",
        constants$38.const$5
    );
}


