// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama;

import java.lang.foreign.Arena;
import java.lang.foreign.MemoryLayout;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SegmentAllocator;
import java.lang.invoke.VarHandle;

/**
 * {@snippet :
 * struct {
 *     intmax_t quot;
 *     intmax_t rem;
 * };
 *}
 */
public class imaxdiv_t {

    public static MemoryLayout $LAYOUT() {
        return constants$5.const$0;
    }

    public static VarHandle quot$VH() {
        return constants$5.const$1;
    }

    /**
     * Getter for field:
     * {@snippet :
     * intmax_t quot;
     *}
     */
    public static long quot$get(MemorySegment seg) {
        return (long) constants$5.const$1.get(seg);
    }

    /**
     * Setter for field:
     * {@snippet :
     * intmax_t quot;
     *}
     */
    public static void quot$set(MemorySegment seg, long x) {
        constants$5.const$1.set(seg, x);
    }

    public static long quot$get(MemorySegment seg, long index) {
        return (long) constants$5.const$1.get(seg.asSlice(index * sizeof()));
    }

    public static void quot$set(MemorySegment seg, long index, long x) {
        constants$5.const$1.set(seg.asSlice(index * sizeof()), x);
    }

    public static VarHandle rem$VH() {
        return constants$5.const$2;
    }

    /**
     * Getter for field:
     * {@snippet :
     * intmax_t rem;
     *}
     */
    public static long rem$get(MemorySegment seg) {
        return (long) constants$5.const$2.get(seg);
    }

    /**
     * Setter for field:
     * {@snippet :
     * intmax_t rem;
     *}
     */
    public static void rem$set(MemorySegment seg, long x) {
        constants$5.const$2.set(seg, x);
    }

    public static long rem$get(MemorySegment seg, long index) {
        return (long) constants$5.const$2.get(seg.asSlice(index * sizeof()));
    }

    public static void rem$set(MemorySegment seg, long index, long x) {
        constants$5.const$2.set(seg.asSlice(index * sizeof()), x);
    }

    public static long sizeof() {
        return $LAYOUT().byteSize();
    }

    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate($LAYOUT());
    }

    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }

    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) {
        return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena);
    }
}


