// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$4 {

    static final FunctionDescriptor JxlDecoderReleaseInput$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderReleaseInput$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderReleaseInput",
        constants$4.JxlDecoderReleaseInput$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetBasicInfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderGetBasicInfo$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetBasicInfo",
        constants$4.JxlDecoderGetBasicInfo$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetExtraChannelInfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderGetExtraChannelInfo$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetExtraChannelInfo",
        constants$4.JxlDecoderGetExtraChannelInfo$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetExtraChannelName$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlDecoderGetExtraChannelName$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetExtraChannelName",
        constants$4.JxlDecoderGetExtraChannelName$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetColorAsEncodedProfile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderGetColorAsEncodedProfile$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetColorAsEncodedProfile",
        constants$4.JxlDecoderGetColorAsEncodedProfile$FUNC
    );
    static final FunctionDescriptor JxlDecoderGetICCProfileSize$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderGetICCProfileSize$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderGetICCProfileSize",
        constants$4.JxlDecoderGetICCProfileSize$FUNC
    );
}


