// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2 {

    static final FunctionDescriptor JxlDecoderCreate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderCreate$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderCreate",
        constants$2.JxlDecoderCreate$FUNC
    );
    static final FunctionDescriptor JxlDecoderReset$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderReset$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderReset",
        constants$2.JxlDecoderReset$FUNC
    );
    static final FunctionDescriptor JxlDecoderDestroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderDestroy$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderDestroy",
        constants$2.JxlDecoderDestroy$FUNC
    );
    static final FunctionDescriptor JxlDecoderRewind$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderRewind$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderRewind",
        constants$2.JxlDecoderRewind$FUNC
    );
    static final FunctionDescriptor JxlDecoderSkipFrames$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle JxlDecoderSkipFrames$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderSkipFrames",
        constants$2.JxlDecoderSkipFrames$FUNC
    );
    static final FunctionDescriptor JxlDecoderDefaultPixelFormat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle JxlDecoderDefaultPixelFormat$MH = RuntimeHelper.downcallHandle(
        "JxlDecoderDefaultPixelFormat",
        constants$2.JxlDecoderDefaultPixelFormat$FUNC
    );
}


