// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface jpegxl_alloc_func {

    java.lang.foreign.Addressable apply(java.lang.foreign.MemoryAddress opaque, long size);
    static MemorySegment allocate(jpegxl_alloc_func fi, MemorySession session) {
        return RuntimeHelper.upcallStub(jpegxl_alloc_func.class, fi, constants$0.jpegxl_alloc_func$FUNC, session);
    }
    static jpegxl_alloc_func ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _opaque, long _size) -> {
            try {
                return (java.lang.foreign.Addressable)(java.lang.foreign.MemoryAddress)constants$0.jpegxl_alloc_func$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_opaque, _size);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


