// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class JxlAnimationHeader {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("tps_numerator"),
        Constants$root.C_INT$LAYOUT.withName("tps_denominator"),
        Constants$root.C_INT$LAYOUT.withName("num_loops"),
        Constants$root.C_INT$LAYOUT.withName("have_timecodes")
    );
    public static MemoryLayout $LAYOUT() {
        return JxlAnimationHeader.$struct$LAYOUT;
    }
    static final VarHandle tps_numerator$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("tps_numerator"));
    public static VarHandle tps_numerator$VH() {
        return JxlAnimationHeader.tps_numerator$VH;
    }
    public static int tps_numerator$get(MemorySegment seg) {
        return (int)JxlAnimationHeader.tps_numerator$VH.get(seg);
    }
    public static void tps_numerator$set( MemorySegment seg, int x) {
        JxlAnimationHeader.tps_numerator$VH.set(seg, x);
    }
    public static int tps_numerator$get(MemorySegment seg, long index) {
        return (int)JxlAnimationHeader.tps_numerator$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void tps_numerator$set(MemorySegment seg, long index, int x) {
        JxlAnimationHeader.tps_numerator$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle tps_denominator$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("tps_denominator"));
    public static VarHandle tps_denominator$VH() {
        return JxlAnimationHeader.tps_denominator$VH;
    }
    public static int tps_denominator$get(MemorySegment seg) {
        return (int)JxlAnimationHeader.tps_denominator$VH.get(seg);
    }
    public static void tps_denominator$set( MemorySegment seg, int x) {
        JxlAnimationHeader.tps_denominator$VH.set(seg, x);
    }
    public static int tps_denominator$get(MemorySegment seg, long index) {
        return (int)JxlAnimationHeader.tps_denominator$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void tps_denominator$set(MemorySegment seg, long index, int x) {
        JxlAnimationHeader.tps_denominator$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle num_loops$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("num_loops"));
    public static VarHandle num_loops$VH() {
        return JxlAnimationHeader.num_loops$VH;
    }
    public static int num_loops$get(MemorySegment seg) {
        return (int)JxlAnimationHeader.num_loops$VH.get(seg);
    }
    public static void num_loops$set( MemorySegment seg, int x) {
        JxlAnimationHeader.num_loops$VH.set(seg, x);
    }
    public static int num_loops$get(MemorySegment seg, long index) {
        return (int)JxlAnimationHeader.num_loops$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void num_loops$set(MemorySegment seg, long index, int x) {
        JxlAnimationHeader.num_loops$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle have_timecodes$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("have_timecodes"));
    public static VarHandle have_timecodes$VH() {
        return JxlAnimationHeader.have_timecodes$VH;
    }
    public static int have_timecodes$get(MemorySegment seg) {
        return (int)JxlAnimationHeader.have_timecodes$VH.get(seg);
    }
    public static void have_timecodes$set( MemorySegment seg, int x) {
        JxlAnimationHeader.have_timecodes$VH.set(seg, x);
    }
    public static int have_timecodes$get(MemorySegment seg, long index) {
        return (int)JxlAnimationHeader.have_timecodes$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void have_timecodes$set(MemorySegment seg, long index, int x) {
        JxlAnimationHeader.have_timecodes$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


