// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_context_get_primary_image_ID",
        constants$8.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_context_get_primary_image_handle",
        constants$8.const$1
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
            JAVA_INT.withName("code"),
            JAVA_INT.withName("subcode"),
            RuntimeHelper.POINTER.withName("message")
        ).withName("heif_error"),
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_context_get_image_handle",
        constants$16.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_context_debug_dump_boxes_to_file",
        constants$16.const$4
    );
}


