// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_height",
        constants$9.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_handle_has_alpha_channel",
        constants$9.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_image_handle_is_premultiplied_alpha",
        constants$9.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_luma_bits_per_pixel",
        constants$9.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_chroma_bits_per_pixel",
        constants$9.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_ispe_width",
        constants$9.const$5
    );
}


