// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {
    }

    static final VarHandle const$0 = constants$54.const$0.varHandle(MemoryLayout.PathElement.groupElement("macOS_compatibility_workaround_no_nclx_profile"));
    static final VarHandle const$1 = constants$54.const$0.varHandle(MemoryLayout.PathElement.groupElement("image_orientation"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "heif_encoding_options_alloc",
        constants$4.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_encoding_options_free",
        constants$0.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_context_encode_image",
        constants$52.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_context_set_primary_image",
        constants$8.const$1
    );
}


