// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$5 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$5() {
    }

    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_get_version_number",
        constants$5.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_get_version_number_major",
        constants$5.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_get_version_number_minor",
        constants$5.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_get_version_number_maintenance",
        constants$5.const$0
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("code"),
        JAVA_INT.withName("subcode"),
        RuntimeHelper.POINTER.withName("message")
    ).withName("heif_error");
}


