// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_metadata_type",
        constants$11.const$1
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_metadata_content_type",
        constants$11.const$1
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_metadata_size",
        constants$25.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_metadata",
        constants$16.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_color_profile_type",
        constants$9.const$5
    );
}


