// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$61 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$61() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_region_get_type",
        constants$9.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_region_get_point",
        constants$14.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_region_get_point_transformed",
        constants$8.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_region_get_rectangle",
        constants$52.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
            JAVA_INT.withName("code"),
            JAVA_INT.withName("subcode"),
            RuntimeHelper.POINTER.withName("message")
        ).withName("heif_error"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_region_get_rectangle_transformed",
        constants$61.const$4
    );
}


