// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_encoder_descriptor_get_compression_format",
        constants$9.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_encoder_descriptor_supports_lossy_compression",
        constants$9.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_encoder_descriptor_supports_lossless_compression",
        constants$9.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_context_get_encoder",
        constants$14.const$3
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_have_decoder_for_format",
        constants$48.const$4
    );
}


