// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$51 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$51() {
    }

    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
            JAVA_INT.withName("code"),
            JAVA_INT.withName("subcode"),
            RuntimeHelper.POINTER.withName("message")
        ).withName("heif_error"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_encoder_parameter_get_valid_integer_values",
        constants$51.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_encoder_parameter_get_valid_string_values",
        constants$8.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(MemoryLayout.structLayout(
            JAVA_INT.withName("code"),
            JAVA_INT.withName("subcode"),
            RuntimeHelper.POINTER.withName("message")
        ).withName("heif_error"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_encoder_set_parameter_integer",
        constants$51.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_encoder_get_parameter_integer",
        constants$14.const$3
    );
}


