// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_ispe_height",
        constants$9.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_handle_has_depth_image",
        constants$9.const$5
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_number_of_depth_images",
        constants$9.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_list_of_depth_image_IDs",
        constants$15.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_depth_image_handle",
        constants$16.const$2
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("version"),
        JAVA_BYTE.withName("has_z_near"),
        JAVA_BYTE.withName("has_z_far"),
        JAVA_BYTE.withName("has_d_min"),
        JAVA_BYTE.withName("has_d_max"),
        MemoryLayout.paddingLayout(3),
        JAVA_DOUBLE.withName("z_near"),
        JAVA_DOUBLE.withName("z_far"),
        JAVA_DOUBLE.withName("d_min"),
        JAVA_DOUBLE.withName("d_max"),
        JAVA_INT.withName("depth_representation_type"),
        JAVA_INT.withName("disparity_reference_view"),
        JAVA_INT.withName("depth_nonlinear_representation_model_size"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("depth_nonlinear_representation_model")
    ).withName("heif_depth_representation_info");
}


