// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {
    }

    static final VarHandle const$0 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("code"));
    static final VarHandle const$1 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("subcode"));
    static final VarHandle const$2 = constants$5.const$5.varHandle(MemoryLayout.PathElement.groupElement("message"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("version")
    ).withName("heif_init_params");
    static final VarHandle const$4 = constants$6.const$3.varHandle(MemoryLayout.PathElement.groupElement("version"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
            JAVA_INT.withName("code"),
            JAVA_INT.withName("subcode"),
            RuntimeHelper.POINTER.withName("message")
        ).withName("heif_error"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "heif_init",
        constants$6.const$5
    );
}


