// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$42 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$42() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_set_content_light_level",
        constants$23.const$4
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("display_primaries_x"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("display_primaries_y"),
        JAVA_SHORT.withName("white_point_x"),
        JAVA_SHORT.withName("white_point_y"),
        JAVA_INT.withName("max_display_mastering_luminance"),
        JAVA_INT.withName("min_display_mastering_luminance")
    ).withName("heif_mastering_display_colour_volume");
    static final VarHandle const$2 = constants$42.const$1.varHandle(MemoryLayout.PathElement.groupElement("white_point_x"));
    static final VarHandle const$3 = constants$42.const$1.varHandle(MemoryLayout.PathElement.groupElement("white_point_y"));
    static final VarHandle const$4 = constants$42.const$1.varHandle(MemoryLayout.PathElement.groupElement("max_display_mastering_luminance"));
    static final VarHandle const$5 = constants$42.const$1.varHandle(MemoryLayout.PathElement.groupElement("min_display_mastering_luminance"));
}


