// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

final class constants$60 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$60() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_region_item_release",
        constants$0.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_region_item_get_reference_size",
        constants$44.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_region_item_get_number_of_regions",
        constants$9.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_region_item_get_list_of_regions",
        constants$15.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_region_release",
        constants$0.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_region_release_many",
        constants$16.const$4
    );
}


