// Generated by jextract

package com.github.gotson.nightmonkeys.heif.lib.panama;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;

import static java.lang.foreign.ValueLayout.*;

/**
 * {@snippet :
 * struct heif_property_user_description {
 *     int version;
 *     char* lang;
 *     char* name;
 *     char* description;
 *     char* tags;
 * };
 *}
 */
public class heif_property_user_description {

    public static MemoryLayout $LAYOUT() {
        return constants$31.const$2;
    }

    public static VarHandle version$VH() {
        return constants$31.const$3;
    }

    /**
     * Getter for field:
     * {@snippet :
     * int version;
     *}
     */
    public static int version$get(MemorySegment seg) {
        return (int) constants$31.const$3.get(seg);
    }

    /**
     * Setter for field:
     * {@snippet :
     * int version;
     *}
     */
    public static void version$set(MemorySegment seg, int x) {
        constants$31.const$3.set(seg, x);
    }

    public static int version$get(MemorySegment seg, long index) {
        return (int) constants$31.const$3.get(seg.asSlice(index * sizeof()));
    }

    public static void version$set(MemorySegment seg, long index, int x) {
        constants$31.const$3.set(seg.asSlice(index * sizeof()), x);
    }

    public static VarHandle lang$VH() {
        return constants$31.const$4;
    }

    /**
     * Getter for field:
     * {@snippet :
     * char* lang;
     *}
     */
    public static MemorySegment lang$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment) constants$31.const$4.get(seg);
    }

    /**
     * Setter for field:
     * {@snippet :
     * char* lang;
     *}
     */
    public static void lang$set(MemorySegment seg, MemorySegment x) {
        constants$31.const$4.set(seg, x);
    }

    public static MemorySegment lang$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment) constants$31.const$4.get(seg.asSlice(index * sizeof()));
    }

    public static void lang$set(MemorySegment seg, long index, MemorySegment x) {
        constants$31.const$4.set(seg.asSlice(index * sizeof()), x);
    }

    public static VarHandle name$VH() {
        return constants$31.const$5;
    }

    /**
     * Getter for field:
     * {@snippet :
     * char* name;
     *}
     */
    public static MemorySegment name$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment) constants$31.const$5.get(seg);
    }

    /**
     * Setter for field:
     * {@snippet :
     * char* name;
     *}
     */
    public static void name$set(MemorySegment seg, MemorySegment x) {
        constants$31.const$5.set(seg, x);
    }

    public static MemorySegment name$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment) constants$31.const$5.get(seg.asSlice(index * sizeof()));
    }

    public static void name$set(MemorySegment seg, long index, MemorySegment x) {
        constants$31.const$5.set(seg.asSlice(index * sizeof()), x);
    }

    public static VarHandle description$VH() {
        return constants$32.const$0;
    }

    /**
     * Getter for field:
     * {@snippet :
     * char* description;
     *}
     */
    public static MemorySegment description$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment) constants$32.const$0.get(seg);
    }

    /**
     * Setter for field:
     * {@snippet :
     * char* description;
     *}
     */
    public static void description$set(MemorySegment seg, MemorySegment x) {
        constants$32.const$0.set(seg, x);
    }

    public static MemorySegment description$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment) constants$32.const$0.get(seg.asSlice(index * sizeof()));
    }

    public static void description$set(MemorySegment seg, long index, MemorySegment x) {
        constants$32.const$0.set(seg.asSlice(index * sizeof()), x);
    }

    public static VarHandle tags$VH() {
        return constants$32.const$1;
    }

    /**
     * Getter for field:
     * {@snippet :
     * char* tags;
     *}
     */
    public static MemorySegment tags$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment) constants$32.const$1.get(seg);
    }

    /**
     * Setter for field:
     * {@snippet :
     * char* tags;
     *}
     */
    public static void tags$set(MemorySegment seg, MemorySegment x) {
        constants$32.const$1.set(seg, x);
    }

    public static MemorySegment tags$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment) constants$32.const$1.get(seg.asSlice(index * sizeof()));
    }

    public static void tags$set(MemorySegment seg, long index, MemorySegment x) {
        constants$32.const$1.set(seg.asSlice(index * sizeof()), x);
    }

    public static long sizeof() {
        return $LAYOUT().byteSize();
    }

    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate($LAYOUT());
    }

    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }

    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) {
        return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena);
    }
}


