// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

/**
 * {@snippet :
 * typedef struct _opaque_pthread_attr_t __darwin_pthread_attr_t;
 *}
 */
public final class __darwin_pthread_attr_t extends _opaque_pthread_attr_t {

    // Suppresses default constructor, ensuring non-instantiability.
    private __darwin_pthread_attr_t() {
    }
}


