// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlSignatureCheck",
        constants$15.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlDecoderCreate",
        constants$17.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "JxlDecoderReset",
        constants$0.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "JxlDecoderDestroy",
        constants$0.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "JxlDecoderRewind",
        constants$0.const$3
    );
}


