// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;

final class constants$25 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$25() {
    }

    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "JxlDecoderSetJPEGBuffer",
        constants$20.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "JxlDecoderReleaseJPEGBuffer",
        constants$19.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "JxlDecoderFlushImage",
        constants$19.const$5
    );
    static final MemorySegment const$3 = MemorySegment.ofAddress(0L);
    static final MemorySegment const$4 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("$INODE64");
    static final MemorySegment const$5 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("$1050");
}


