// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;

import static java.lang.foreign.ValueLayout.JAVA_INT;

final class constants$16 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$16() {
    }

    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(JxlParallelRunFunction.class, "apply", constants$15.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$15.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(JxlParallelRunner.class, "apply", constants$16.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$16.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT);
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "JxlDecoderVersion",
        constants$16.const$5
    );
}


