// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;

import static java.lang.foreign.ValueLayout.JAVA_LONG;

final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {
    }

    static final VarHandle const$0 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("duration"));
    static final VarHandle const$1 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("timecode"));
    static final VarHandle const$2 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("name_length"));
    static final VarHandle const$3 = constants$12.const$5.varHandle(MemoryLayout.PathElement.groupElement("is_last"));
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(jpegxl_alloc_func.class, "apply", constants$13.const$4);
}


