// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

/**
 * {@snippet :
 * typedef struct JxlDecoderStruct JxlDecoder;
 *}
 */
public final class JxlDecoder {

    // Suppresses default constructor, ensuring non-instantiability.
    private JxlDecoder() {
    }
}


