// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     uint32_t xsize;
 *     uint32_t ysize;
 * }
 * }
 */
public class JxlPreviewHeader {

    JxlPreviewHeader() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        decode_h.C_INT.withName("xsize"),
        decode_h.C_INT.withName("ysize")
    ).withName("$anon$65:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt xsize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("xsize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t xsize
     * }
     */
    public static final OfInt xsize$layout() {
        return xsize$LAYOUT;
    }

    private static final long xsize$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t xsize
     * }
     */
    public static final long xsize$offset() {
        return xsize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t xsize
     * }
     */
    public static int xsize(MemorySegment struct) {
        return struct.get(xsize$LAYOUT, xsize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t xsize
     * }
     */
    public static void xsize(MemorySegment struct, int fieldValue) {
        struct.set(xsize$LAYOUT, xsize$OFFSET, fieldValue);
    }

    private static final OfInt ysize$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ysize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t ysize
     * }
     */
    public static final OfInt ysize$layout() {
        return ysize$LAYOUT;
    }

    private static final long ysize$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t ysize
     * }
     */
    public static final long ysize$offset() {
        return ysize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t ysize
     * }
     */
    public static int ysize(MemorySegment struct) {
        return struct.get(ysize$LAYOUT, ysize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t ysize
     * }
     */
    public static void ysize(MemorySegment struct, int fieldValue) {
        struct.set(ysize$LAYOUT, ysize$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

