// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama.webp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$19 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$19() {}
    static final VarHandle const$0 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("bypass_filtering"));
    static final VarHandle const$1 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("no_fancy_upsampling"));
    static final VarHandle const$2 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("use_cropping"));
    static final VarHandle const$3 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("crop_left"));
    static final VarHandle const$4 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("crop_top"));
    static final VarHandle const$5 = constants$18.const$5.varHandle(MemoryLayout.PathElement.groupElement("crop_width"));
}


