// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama.webp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("y"),
        RuntimeHelper.POINTER.withName("u"),
        RuntimeHelper.POINTER.withName("v"),
        RuntimeHelper.POINTER.withName("a"),
        JAVA_INT.withName("y_stride"),
        JAVA_INT.withName("u_stride"),
        JAVA_INT.withName("v_stride"),
        JAVA_INT.withName("a_stride"),
        JAVA_LONG.withName("y_size"),
        JAVA_LONG.withName("u_size"),
        JAVA_LONG.withName("v_size"),
        JAVA_LONG.withName("a_size")
    ).withName("WebPYUVABuffer");
    static final VarHandle const$1 = constants$11.const$0.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$2 = constants$11.const$0.varHandle(MemoryLayout.PathElement.groupElement("u"));
    static final VarHandle const$3 = constants$11.const$0.varHandle(MemoryLayout.PathElement.groupElement("v"));
    static final VarHandle const$4 = constants$11.const$0.varHandle(MemoryLayout.PathElement.groupElement("a"));
    static final VarHandle const$5 = constants$11.const$0.varHandle(MemoryLayout.PathElement.groupElement("y_stride"));
}


