// Generated by jextract

package com.github.gotson.nightmonkeys.webp.lib.panama.webp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final VarHandle const$0 = constants$11.const$0.varHandle(MemoryLayout.PathElement.groupElement("a_size"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("colorspace"),
        JAVA_INT.withName("width"),
        JAVA_INT.withName("height"),
        JAVA_INT.withName("is_external_memory"),
        MemoryLayout.unionLayout(
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("rgba"),
                JAVA_INT.withName("stride"),
                MemoryLayout.paddingLayout(4),
                JAVA_LONG.withName("size")
            ).withName("RGBA"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("y"),
                RuntimeHelper.POINTER.withName("u"),
                RuntimeHelper.POINTER.withName("v"),
                RuntimeHelper.POINTER.withName("a"),
                JAVA_INT.withName("y_stride"),
                JAVA_INT.withName("u_stride"),
                JAVA_INT.withName("v_stride"),
                JAVA_INT.withName("a_stride"),
                JAVA_LONG.withName("y_size"),
                JAVA_LONG.withName("u_size"),
                JAVA_LONG.withName("v_size"),
                JAVA_LONG.withName("a_size")
            ).withName("YUVA")
        ).withName("u"),
        MemoryLayout.sequenceLayout(4, JAVA_INT).withName("pad"),
        RuntimeHelper.POINTER.withName("private_memory")
    ).withName("WebPDecBuffer");
    static final VarHandle const$2 = constants$13.const$1.varHandle(MemoryLayout.PathElement.groupElement("colorspace"));
    static final VarHandle const$3 = constants$13.const$1.varHandle(MemoryLayout.PathElement.groupElement("width"));
    static final VarHandle const$4 = constants$13.const$1.varHandle(MemoryLayout.PathElement.groupElement("height"));
    static final VarHandle const$5 = constants$13.const$1.varHandle(MemoryLayout.PathElement.groupElement("is_external_memory"));
}


