// Generated by jextract

package com.github.gotson.nightmonkeys.jxl.lib.panama;

import jdk.incubator.foreign.GroupLayout;
import jdk.incubator.foreign.MemoryAddress;
import jdk.incubator.foreign.MemoryLayout;
import jdk.incubator.foreign.MemorySegment;
import jdk.incubator.foreign.ResourceScope;
import jdk.incubator.foreign.SegmentAllocator;

import java.lang.invoke.VarHandle;

public class JxlColorEncoding {

    static final GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("color_space"),
        Constants$root.C_INT$LAYOUT.withName("white_point"),
        MemoryLayout.sequenceLayout(2, Constants$root.C_DOUBLE$LAYOUT).withName("white_point_xy"),
        Constants$root.C_INT$LAYOUT.withName("primaries"),
        MemoryLayout.paddingLayout(32),
        MemoryLayout.sequenceLayout(2, Constants$root.C_DOUBLE$LAYOUT).withName("primaries_red_xy"),
        MemoryLayout.sequenceLayout(2, Constants$root.C_DOUBLE$LAYOUT).withName("primaries_green_xy"),
        MemoryLayout.sequenceLayout(2, Constants$root.C_DOUBLE$LAYOUT).withName("primaries_blue_xy"),
        Constants$root.C_INT$LAYOUT.withName("transfer_function"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_DOUBLE$LAYOUT.withName("gamma"),
        Constants$root.C_INT$LAYOUT.withName("rendering_intent"),
        MemoryLayout.paddingLayout(32)
    );

    public static MemoryLayout $LAYOUT() {
        return JxlColorEncoding.$struct$LAYOUT;
    }

    static final VarHandle color_space$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("color_space"));

    public static VarHandle color_space$VH() {
        return JxlColorEncoding.color_space$VH;
    }

    public static int color_space$get(MemorySegment seg) {
        return (int) JxlColorEncoding.color_space$VH.get(seg);
    }

    public static void color_space$set(MemorySegment seg, int x) {
        JxlColorEncoding.color_space$VH.set(seg, x);
    }

    public static int color_space$get(MemorySegment seg, long index) {
        return (int) JxlColorEncoding.color_space$VH.get(seg.asSlice(index * sizeof()));
    }

    public static void color_space$set(MemorySegment seg, long index, int x) {
        JxlColorEncoding.color_space$VH.set(seg.asSlice(index * sizeof()), x);
    }

    static final VarHandle white_point$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("white_point"));

    public static VarHandle white_point$VH() {
        return JxlColorEncoding.white_point$VH;
    }

    public static int white_point$get(MemorySegment seg) {
        return (int) JxlColorEncoding.white_point$VH.get(seg);
    }

    public static void white_point$set(MemorySegment seg, int x) {
        JxlColorEncoding.white_point$VH.set(seg, x);
    }

    public static int white_point$get(MemorySegment seg, long index) {
        return (int) JxlColorEncoding.white_point$VH.get(seg.asSlice(index * sizeof()));
    }

    public static void white_point$set(MemorySegment seg, long index, int x) {
        JxlColorEncoding.white_point$VH.set(seg.asSlice(index * sizeof()), x);
    }

    public static MemorySegment white_point_xy$slice(MemorySegment seg) {
        return seg.asSlice(8, 16);
    }

    static final VarHandle primaries$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("primaries"));

    public static VarHandle primaries$VH() {
        return JxlColorEncoding.primaries$VH;
    }

    public static int primaries$get(MemorySegment seg) {
        return (int) JxlColorEncoding.primaries$VH.get(seg);
    }

    public static void primaries$set(MemorySegment seg, int x) {
        JxlColorEncoding.primaries$VH.set(seg, x);
    }

    public static int primaries$get(MemorySegment seg, long index) {
        return (int) JxlColorEncoding.primaries$VH.get(seg.asSlice(index * sizeof()));
    }

    public static void primaries$set(MemorySegment seg, long index, int x) {
        JxlColorEncoding.primaries$VH.set(seg.asSlice(index * sizeof()), x);
    }

    public static MemorySegment primaries_red_xy$slice(MemorySegment seg) {
        return seg.asSlice(32, 16);
    }

    public static MemorySegment primaries_green_xy$slice(MemorySegment seg) {
        return seg.asSlice(48, 16);
    }

    public static MemorySegment primaries_blue_xy$slice(MemorySegment seg) {
        return seg.asSlice(64, 16);
    }

    static final VarHandle transfer_function$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("transfer_function"));

    public static VarHandle transfer_function$VH() {
        return JxlColorEncoding.transfer_function$VH;
    }

    public static int transfer_function$get(MemorySegment seg) {
        return (int) JxlColorEncoding.transfer_function$VH.get(seg);
    }

    public static void transfer_function$set(MemorySegment seg, int x) {
        JxlColorEncoding.transfer_function$VH.set(seg, x);
    }

    public static int transfer_function$get(MemorySegment seg, long index) {
        return (int) JxlColorEncoding.transfer_function$VH.get(seg.asSlice(index * sizeof()));
    }

    public static void transfer_function$set(MemorySegment seg, long index, int x) {
        JxlColorEncoding.transfer_function$VH.set(seg.asSlice(index * sizeof()), x);
    }

    static final VarHandle gamma$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("gamma"));

    public static VarHandle gamma$VH() {
        return JxlColorEncoding.gamma$VH;
    }

    public static double gamma$get(MemorySegment seg) {
        return (double) JxlColorEncoding.gamma$VH.get(seg);
    }

    public static void gamma$set(MemorySegment seg, double x) {
        JxlColorEncoding.gamma$VH.set(seg, x);
    }

    public static double gamma$get(MemorySegment seg, long index) {
        return (double) JxlColorEncoding.gamma$VH.get(seg.asSlice(index * sizeof()));
    }

    public static void gamma$set(MemorySegment seg, long index, double x) {
        JxlColorEncoding.gamma$VH.set(seg.asSlice(index * sizeof()), x);
    }

    static final VarHandle rendering_intent$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("rendering_intent"));

    public static VarHandle rendering_intent$VH() {
        return JxlColorEncoding.rendering_intent$VH;
    }

    public static int rendering_intent$get(MemorySegment seg) {
        return (int) JxlColorEncoding.rendering_intent$VH.get(seg);
    }

    public static void rendering_intent$set(MemorySegment seg, int x) {
        JxlColorEncoding.rendering_intent$VH.set(seg, x);
    }

    public static int rendering_intent$get(MemorySegment seg, long index) {
        return (int) JxlColorEncoding.rendering_intent$VH.get(seg.asSlice(index * sizeof()));
    }

    public static void rendering_intent$set(MemorySegment seg, long index, int x) {
        JxlColorEncoding.rendering_intent$VH.set(seg.asSlice(index * sizeof()), x);
    }

    public static long sizeof() {
        return $LAYOUT().byteSize();
    }

    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate($LAYOUT());
    }

    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }

    public static MemorySegment allocate(ResourceScope scope) {
        return allocate(SegmentAllocator.nativeAllocator(scope));
    }

    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }

    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) {
        return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope);
    }
}


